dist: trusty
sudo: required
language: cpp

notifications:
 email: false

os:
 - linux
 - osx

compiler:
 - gcc
 - clang

script:
 - mkdir build
 - cd build
 - cmake --version
 - cmake ..
 - cmake --build . -- -j4

after_success:
 - ctest -j4
