dist: trusty
sudo: required
language: cpp

notifications:
 email: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.6
          packages:
            - clang-3.6
      env:
        - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.8
          packages:
            - clang-3.8
      env:
        - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    # Clang 4.9
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew update && (brew outdated gcc5 || brew upgrade gcc5) && brew install gcc5 && CC=gcc-5 && CXX=g++-5"
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew update && (brew outdated gcc6 || brew upgrade gcc6) && brew install gcc6 && CC=gcc-6 && CXX=g++-6"
    - os: osx
      osx_image: xcode9.3
      env:
        - MATRIX_EVAL="brew cask uninstall oclint && brew install gcc@7 && CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"

script:
 - mkdir build
 - cd build
 - cmake --version
 - cmake ..
 - cmake --build . -- -j4

after_success:
 - ctest -j4
