dist: trusty
sudo: required
language: cpp

notifications:
 email: false

os:
 - linux
 - osx

compiler:
 - gcc
 - clang

addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - g++-5

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" && "$CC" == "gcc"]; then CC=/usr/bin/gcc-5 && CXX=/usr/bin/g++-5 ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" && "$CC" == "gcc"]; then CC=gcc-4.9 && CXX=g++-4.9 ; fi
  # TODO Use all availble versions of gcc and clang on osx and linux: https://docs.travis-ci.com/user/languages/c/#GCC-on-OS-X

script:
 - mkdir build
 - cd build
 - cmake --version
 - cmake ..
 - cmake --build . -- -j4

after_success:
 - ctest -j4
