dist: trusty
sudo: required
language: cpp

notifications:
 email: false

addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - g++-5
   - lcov

script:
 - mkdir build
 - cd build
 - cmake --version
 - CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake ..
 - cmake --build . -- -j4

after_success:
 - ctest -j4
 - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-5
